### ISSUE TITLE
Add the 'current location' button

### ISSUE THREAD

**Issue by mvysny** [FlowingCode/GoogleMapsAddon#114]
The web Google Maps has this "crosshair" current location button available, please see screenshot for more details. Would it be possible to add an API to show the button?

![image](https://github.com/FlowingCode/GoogleMapsAddon/assets/254091/25245ea7-1c71-4de2-a7be-0de8cf4aaab4)

**Comment by mvysny** [comment]
Looks like it's not baked in the Google Maps JavaScript API:
1. The initial demo of the component at https://developers.google.com/maps/documentation/javascript/overview doesn't show the crosshair button
2. There's a documentation to add the "Current location" button here: https://developers.google.com/maps/documentation/javascript/geolocation

**Comment by mvysny** [comment]
See solution in #115

**Comment by javier-godoy** [comment]
Hello. With support for the Controls API (#115), the current location button would be just an example on how to call `goToCurrentLocation` from a custom control, and we should update the geolocation example in [demo](https://addonsv24.flowingcode.com/googlemaps/geolocation) so that it uses the new API. 

We'll keep this issue open until #115 is resolved.
