### ISSUE TITLE
Add/remove custom controls dynamically

### ISSUE THREAD

**Issue by paodb** [FlowingCode/GoogleMapsAddon#128]
### Feature proposal

Currently there seems not possible to add and remove custom controls dynamically (taken from https://github.com/FlowingCode/GoogleMapsAddon/issues/127#issuecomment-2113398747)

**Comment by JariHanah** [comment]
Thanks for openning this issue, 
Currently I have a use case where I need to navigate between data presented on the map. I have fixed buttons, I also have buttons that might be added by the user to filter the data. The user might ask to remove some filters all together, 

I can possibly use the setCustomControls you recommended  with removeAllCustomButtons you plan to add.  
![image](https://github.com/FlowingCode/GoogleMapsAddon/assets/71745537/75f99159-d148-4d6b-aec8-ca9784bf6b67)

**Comment by JariHanah** [comment]
To help with this, 
I have written a code as a work around that solves the issue.
Even though the issue seems resolved with this code, after some updates and resetting the buttons, occasionally some of the newly inserted buttons gets inserted in a different position. not sure why. Not sure if it pertains to the same issue. or what is causing it. In any case, this new setCustomControls method, does help me add and remove buttons dynamically. 


`
static class CustomControl2 extends CustomControl {
        CustomControl2(Button b, ControlPosition pos) {
            super(b, pos);
        }

        public JsonObject getJson(int i) {
            return super.getJson(i);
        }
    }

List<Element[]> elements = new ArrayList<>();

    public void setControls(CustomControl2[] customControls) {
        JsonArray jsonArray = Json.createArray();
        elements.forEach(element -> {
            Arrays.stream(element).forEach(element1 -> {
                if (element1 != null) {
                    gmaps.getElement().removeChild(element1);
                }
            });

        });
        elements.clear();
        for (int i = 0; i < customControls.length; ++i) {
            CustomControl2 customControl = customControls[i];
            jsonArray.set(i, customControl.getJson(i));
            customControl.getControlButton().getElement().setAttribute("slot", "customControlSlot_" + i);
            Element p = gmaps.getElement();
            Element[] e = new Element[]{customControl.getControlButton().getElement()};
            gmaps.getElement().appendChild(e);
            elements.add(e);
        }
        gmaps.getElement().setPropertyJson("customControls", jsonArray);
    }
`
